import React,{useEffect,useMemo,useRef,useState} from 'react';
import {ArrowRightIcon,ArrowUpRightIcon,BookmarkSimpleIcon,MagnifyingGlassIcon,XIcon,DownloadSimpleIcon,ArrowLeftIcon,ArrowClockwiseIcon} from '@phosphor-icons/react';
import {copy} from './copy';
import {readState,rankProjects,usageRows,priceValue,routes} from './data';
const root=import.meta.env.BASE_URL;
const short=n=>n==null?'—':new Intl.NumberFormat('en',{notation:'compact',maximumFractionDigits:1}).format(n);
const number=n=>n==null?'—':new Intl.NumberFormat('en').format(n);
function useJson(path){const [data,setData]=useState(null),[error,setError]=useState(false),[retry,setRetry]=useState(0);useEffect(()=>{let cancelled=false;setData(null);setError(false);fetch(root+path).then(r=>{if(!r.ok)throw Error(r.status);return r.json()}).then(d=>{if(!cancelled)setData(d)}).catch(()=>{if(!cancelled)setError(true)});return()=>{cancelled=true}},[path,retry]);return {data,error,retry:()=>setRetry(x=>x+1)}}
function Chart({data,t}){const ref=useRef(null);useEffect(()=>{let chart;let cancelled=false;let observer;import('./chart').then(({createChart})=>{if(cancelled)return;chart=createChart(ref.current,data);observer=new ResizeObserver(()=>chart.resize());observer.observe(ref.current)});return()=>{cancelled=true;observer?.disconnect();chart?.dispose()}},[data]);return <div ref={ref} className="chart" role="img" aria-label={t.chartLabel}/>}
function Empty({t,baseline=false,reset}){return <div className="empty"><span className="eyebrow">{baseline?'720H':'0 '+t.count}</span><h3>{baseline?t.baseline:t.noResults}</h3><p>{baseline?t.baselineDesc:t.noResultsDesc}</p>{reset&&!baseline&&<button className="solid" onClick={reset}>{t.reset}<ArrowClockwiseIcon/></button>}</div>}
function Loading({resource,t}){return <div className="empty" role="status"><p>{resource.error?t.error:t.loading}</p>{resource.error&&<button className="solid" onClick={resource.retry}>{t.retry}</button>}</div>}
function CSVButton({rows,name,t}){function save(){const keys=Object.keys(rows[0]||{});const val=v=>'"'+String(v??'').replaceAll('"','""')+'"';const blob=new Blob(['\ufeff'+[keys.map(val).join(','),...rows.map(r=>keys.map(k=>val(r[k])).join(','))].join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}return <button className="text-button" onClick={save} disabled={!rows.length}><DownloadSimpleIcon/>{t.export}</button>}
export default function App(){
 const [state,setState]=useState(readState);const {page,lang,channel,period}=state;const t=copy[lang];
 const [query,setQuery]=useState(''),[projectLang,setProjectLang]=useState('all'),[savedOnly,setSavedOnly]=useState(false),[currency,setCurrency]=useState('USD'),[provider,setProvider]=useState('all'),[openOnly,setOpenOnly]=useState(false),[sort,setSort]=useState('input'),[range,setRange]=useState(12),[modal,setModal]=useState(null);
 const [saved,setSaved]=useState(()=>{try{return JSON.parse(localStorage.getItem('penguin-saved')||'[]')}catch{return []}});
 const projects=useJson(`data/${channel}/${period}.json`),modelData=useJson('data/models.json'),status=useJson('data/status.json');
 const dialog=useRef(null);
 function change(p){setState(s=>({...s,...p}));if(p.page&&p.page!==page){setQuery('');setModal(null);window.scrollTo({top:0,behavior:'instant'})}}
 useEffect(()=>{const p=new URLSearchParams(location.search);p.set('page',page);p.set('lang',lang);p.set('channel',channel);p.set('period',period);const url=location.pathname+'?'+p; if(location.search!=='?'+p)history.pushState(null,'',url);document.documentElement.lang=lang==='zh'?'zh-CN':'en';document.title=(page==='home'?t.brand:t[page]+' | '+t.brand);try{localStorage.setItem('penguin-locale',lang)}catch{}},[page,lang,channel,period]);
 useEffect(()=>{const back=()=>{setState(readState());setModal(null)};window.addEventListener('popstate',back);return()=>window.removeEventListener('popstate',back)},[]);
 useEffect(()=>{try{localStorage.setItem('penguin-saved',JSON.stringify(saved))}catch{}},[saved]);
 useEffect(()=>{if(modal)dialog.current?.showModal();else dialog.current?.close()},[modal]);
 const ranked=useMemo(()=>rankProjects(projects.data||[]),[projects.data]);
 const projectRows=ranked.filter(r=>(!query||(r.name+' '+r.fullName+' '+r.language).toLowerCase().includes(query.toLowerCase()))&&(projectLang==='all'||r.language===projectLang)&&(!savedOnly||saved.includes(r.repositoryId)));
 const trendData=useMemo(()=>modelData.data?usageRows(modelData.data.trends,range):null,[modelData.data,range]);
 const pricing=(modelData.data?.prices.models||[]).filter(r=>(r.status??'active')==='active');
 const priceRows=pricing.filter(r=>(r.name+' '+r.provider_name).toLowerCase().includes(query.toLowerCase())&&(provider==='all'||r.provider===provider)&&(!openOnly||r.is_open_source)).sort((a,b)=>sort==='context'?b.context_length-a.context_length:(priceValue(a,currency,sort)??Infinity)-(priceValue(b,currency,sort)??Infinity));
 const formatPrice=r=>v=>v==null?'—':new Intl.NumberFormat(lang==='zh'?'zh-CN':'en-US',{style:'currency',currency:r,minimumFractionDigits:2,maximumFractionDigits:4}).format(v);
 const date=s=>s?new Intl.DateTimeFormat(lang==='zh'?'zh-CN':'en-US',{year:'numeric',month:'short',day:'numeric',timeZone:'Asia/Shanghai'}).format(new Date(s)):'—';
 const href=p=>`?page=${p}&lang=${lang}&channel=${channel}&period=${period}`;
 const link=(p,text,cls='')=><a className={cls} href={href(p)} onClick={e=>{e.preventDefault();change({page:p})}}>{text}</a>;
 const cta=p=>link(p,<>{t.view}<ArrowRightIcon size={23}/></>,'inline-link');
 const activeModels=trendData?.rows.filter(r=>(r.name+' '+r.provider).toLowerCase().includes(query.toLowerCase()))||[];
 const homeUsage=useMemo(()=>modelData.data?usageRows(modelData.data.trends,4):null,[modelData.data]);
 const homePrices=[...pricing].sort((a,b)=>(priceValue(a,currency,'input')??Infinity)-(priceValue(b,currency,'input')??Infinity)).slice(0,5);
 const renderProjects=()=>(<><div className="tabs" role="tablist" aria-label={t.opensource}>{[['product','products'],['skill','skills'],['dsh','ecosystem']].map(([id,key])=><button key={id} role="tab" aria-selected={channel===id} onClick={()=>change({channel:id})}>{t[key]}</button>)}</div><div className="toolbar"><div className="segmented" aria-label={t.periodLabel}>{['daily','weekly','monthly'].map(x=><button key={x} aria-pressed={period===x} onClick={()=>change({period:x})}>{t[x]}</button>)}</div><Search value={query} onChange={setQuery} label={t.search}/><select aria-label={t.language} value={projectLang} onChange={e=>setProjectLang(e.target.value)}><option value="all">{t.allLanguages}</option>{[...new Set(ranked.map(r=>r.language).filter(Boolean))].sort().map(x=><option key={x}>{x}</option>)}</select><label className="check"><input type="checkbox" checked={savedOnly} onChange={e=>setSavedOnly(e.target.checked)}/>{t.favorites}</label></div>
 {!projects.data?<Loading resource={projects} t={t}/>:!projectRows.length?<Empty t={t} baseline={!ranked.length} reset={()=>{setQuery('');setProjectLang('all');setSavedOnly(false)}}/>:<div className="table-scroll"><table className="project-table"><thead><tr><th>{t.rank}</th><th>{t.project}</th><th>{t.growth}</th><th>{t.stars}</th><th>{t.language}</th><th><BookmarkSimpleIcon aria-label={t.save}/></th></tr></thead><tbody>{projectRows.map(r=><tr key={r.repositoryId}><td className="ranking">{String(ranked.indexOf(r)+1).padStart(2,'0')}</td><td><button className="project-name" onClick={()=>setModal({type:'project',item:r})}>{r.name}<ArrowUpRightIcon size={17}/></button><p className="repo-name">{r.fullName}</p><p className="description">{lang==='zh'?(r.capabilitiesZh?.[0]||r.descriptionZh):r.descriptionEn}</p></td><td className="growth">+{number(r.starGrowth)}<small>{t.periodGrowth}</small></td><td className="numeric">{short(r.stars)}<small className="mobile-stat-label">{t.stars}</small></td><td><span className="code-label">{r.language||'—'}</span></td><td><button className="icon-button" aria-label={(saved.includes(r.repositoryId)?t.unsave:t.save)+' '+r.name} aria-pressed={saved.includes(r.repositoryId)} onClick={()=>toggleSave(r.repositoryId)}><BookmarkSimpleIcon weight={saved.includes(r.repositoryId)?'fill':'regular'}/></button></td></tr>)}</tbody></table></div>}<p className="dataset-note">{t.previewNotice}</p></>);
 function toggleSave(id){setSaved(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id])}
 return <><a className="skip" href="#main">{t.skip}</a><div className="publisher"><div className="frame publisher-inner"><img src={root+'assets/tencent-technology.png'} alt="腾讯科技 Tencent Technology"/><div className="locale" aria-label="Language / 语言"><button onClick={()=>change({lang:'en'})} aria-pressed={lang==='en'}>English</button><span aria-hidden="true">|</span><button onClick={()=>change({lang:'zh'})} aria-pressed={lang==='zh'}>简体中文</button></div></div></div>
 <header className="frame masthead">{link('home',<><div className="brand-mark"><img src={root+'assets/penguin-mark.png'} alt=""/></div><div><strong>{t.brand}</strong><span>{t.subbrand}</span></div></>,'brand')}<nav aria-label={lang==='en'?'Main navigation':'主导航'}>{routes.map(p=><a key={p} href={href(p)} aria-current={page===p?'page':undefined} onClick={e=>{e.preventDefault();change({page:p})}}>{t[p]}</a>)}</nav></header>
 <main id="main" className={'frame '+(page==='home'?'home':'inner-page')}>
 {page==='home'?<><section className="hero"><div><p className="eyebrow">{t.eyebrow}</p><h1>{t.hero}<span>.</span></h1><p className="tagline">{t.tagline}</p></div><div className="manifesto">{t.manifesto.map(x=><div key={x}>{x}</div>)}<i/></div></section>
 <div className="home-jumps"><a href="#home-projects">{t.opensourceTitle}<ArrowRightIcon/></a><a href="#home-usage">{t.usageTitle}<ArrowRightIcon/></a><a href="#home-prices">{t.pricingTitle}<ArrowRightIcon/></a></div>
 <div className="home-layout"><section id="home-projects" className="home-projects" aria-label={t.opensourceTitle}><div className="home-section-head"><div><p className="eyebrow">OPEN SOURCE / TOP 10</p><h2>{t.opensourceTitle}</h2></div>{cta('opensource')}</div>{renderProjects()}</section>
 <aside className="home-sidebar"><section id="home-usage" className="home-digest usage-digest"><div className="home-section-head"><div><p className="eyebrow">MODEL USAGE</p><h2>{t.usageTitle}</h2></div></div><p className="digest-caption">{t.last4} · TOP 5</p>{!homeUsage?<Loading resource={modelData} t={t}/>:<ol className="digest-list">{homeUsage.rows.slice(0,5).map((r,i)=><li key={r.id}><span className="digest-rank">{String(i+1).padStart(2,'0')}</span><div>{link('usage',r.name,'digest-name')}<small>{r.provider}</small></div><strong>{short(r.total)}</strong></li>)}</ol>}{cta('usage')}</section>
 <section id="home-prices" className="home-digest"><div className="home-section-head"><div><p className="eyebrow">API PRICING</p><h2>{t.pricingTitle}</h2></div></div><div className="digest-currency"><p className="digest-caption">{t.input} · {t.perMillion}</p><div className="segmented" aria-label={t.currency}>{['USD','CNY'].map(c=><button key={c} onClick={()=>setCurrency(c)} aria-pressed={currency===c}>{c}</button>)}</div></div>{!modelData.data?<Loading resource={modelData} t={t}/>:<ol className="digest-list price-digest">{homePrices.map((r,i)=><li key={r.slug}><span className="digest-rank">{String(i+1).padStart(2,'0')}</span><div><button className="digest-name" onClick={()=>setModal({type:'price',item:r})}>{r.name}</button><small>{r.provider_name}</small></div><strong>{formatPrice(currency)(priceValue(r,currency,'input'))}</strong></li>)}</ol>}{cta('pricing')}</section>
 <section className="home-benchmark"><p className="eyebrow">UP NEXT / 01</p><h2>{link('benchmarks',t.benchmarkTitle)}</h2><p>{t.benchmarkDesc}</p><span className="badge">{t.soon}</span></section></aside></div>
 <section className="home-chart"><div className="home-section-head"><div><p className="eyebrow">THE BIGGER PICTURE</p><h2>{t.trend}</h2></div>{cta('usage')}</div><p className="digest-caption">{t.last4} · {t.top10}</p>{homeUsage?<><Chart data={homeUsage} t={t}/><p className="quiet">{t.chartHelp}</p></>:<Loading resource={modelData} t={t}/>}</section></>:

 <><div className="page-heading"><p className="eyebrow">{page==='benchmarks'?'01 / BENCHMARKS':page==='usage'?'02 / USAGE':page==='pricing'?'03 / PRICING':'04 / OPEN SOURCE'}</p><h1>{t[page==='benchmarks'?'benchmarkTitle':page+'Title']}<span>.</span></h1><p>{t[page==='benchmarks'?'benchmarkDesc':page+'Desc']}</p></div>
 {page==='benchmarks'&&<section className="benchmark-empty"><span className="badge">{t.soon}</span><h2>{t.benchmarkDesc}</h2><p>{t.benchmarkBody}</p>{link('usage',<>{t.explore}<ArrowRightIcon/></>,'solid')}{link('home',<><ArrowLeftIcon/>{t.back}</>,'text-button')}</section>}
 {page==='opensource'&&renderProjects()}
 {page==='usage'&&(!trendData?<Loading resource={modelData} t={t}/>:<><div className="toolbar"><select aria-label={t.periodLabel} value={range} onChange={e=>setRange(Number(e.target.value))}>{[4,12,26].map(n=><option value={n} key={n}>{t['last'+n]}</option>)}</select><span className="quiet">{t.fullWeeks}</span><CSVButton t={t} name="penguin-model-usage" rows={trendData.rows.map(r=>({[t.model]:r.name,[t.provider]:r.provider,[t.tokens]:r.total}))}/></div><div className="stats"><div><span>{t.totalTokens}</span><strong>{short(trendData.rows.reduce((s,r)=>s+r.total,0))}</strong></div><div><span>{t.models}</span><strong>{trendData.rows.length}</strong></div><div><span>{t.dataCoverage}</span><strong className="date-range">{date(trendData.weeks[0]?.[0])}<span className="range-separator"> – </span>{date(trendData.weeks.at(-1)?.[0])}</strong></div></div><section className="chart-panel"><div className="section-head"><h2>{t.trend}</h2><span className="code-label">{t.top10}</span></div><Chart data={trendData} t={t}/><p className="quiet">{t.chartHelp}</p></section><div className="section-head"><h2>{t.usageTable}</h2><Search value={query} onChange={setQuery} label={t.searchModels}/></div>{!activeModels.length?<Empty t={t} reset={()=>setQuery('')}/>:<div className="table-scroll"><table><thead><tr><th>{t.rank}</th><th>{t.model}</th><th>{t.provider}</th><th>{t.tokens}</th></tr></thead><tbody>{activeModels.map(r=><tr key={r.id}><td className="ranking">{String(trendData.rows.indexOf(r)+1).padStart(2,'0')}</td><td className="model-name">{r.name}</td><td>{r.provider}</td><td className="numeric">{short(r.total)}</td></tr>)}</tbody></table></div>}</>)}
 {page==='pricing'&&(!modelData.data?<Loading resource={modelData} t={t}/>:<><div className="toolbar"><Search value={query} onChange={setQuery} label={t.searchModels}/><select aria-label={t.provider} value={provider} onChange={e=>setProvider(e.target.value)}><option value="all">{t.allProviders}</option>{[...new Map(pricing.map(r=>[r.provider,r.provider_name]))].sort((a,b)=>a[1].localeCompare(b[1])).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select><div className="segmented" aria-label={t.currency}>{['USD','CNY'].map(c=><button key={c} onClick={()=>setCurrency(c)} aria-pressed={currency===c}>{c}</button>)}</div><select aria-label={t.sort} value={sort} onChange={e=>setSort(e.target.value)}><option value="input">{t.lowInput}</option><option value="output">{t.lowOutput}</option><option value="context">{t.highContext}</option></select><label className="check"><input type="checkbox" checked={openOnly} onChange={e=>setOpenOnly(e.target.checked)}/>{t.openOnly}</label></div><div className="section-head"><span className="code-label">{priceRows.length} {t.count} · {t.perMillion}</span><CSVButton t={t} name={'penguin-pricing-'+currency} rows={priceRows.map(r=>({[t.model]:r.name,[t.provider]:r.provider_name,[t.currency]:currency,[t.input]:priceValue(r,currency,'input'),[t.output]:priceValue(r,currency,'output')}))}/></div>{!priceRows.length?<Empty t={t} reset={()=>{setQuery('');setProvider('all');setOpenOnly(false)}}/>:<div className="table-scroll"><table className="price-table"><thead><tr><th>{t.model}</th><th>{t.provider}</th><th>{t.input}</th><th>{t.output}</th><th>{t.context}</th></tr></thead><tbody>{priceRows.map(r=><tr key={r.slug}><td><button className="project-name" onClick={()=>setModal({type:'price',item:r})}>{r.name}<ArrowUpRightIcon size={16}/></button>{r.is_open_source&&<small className="quiet">{lang==='zh'?'开放权重':'Open weights'}</small>}</td><td>{r.provider_name}</td><td className="numeric">{formatPrice(currency)(priceValue(r,currency,'input'))}</td><td className="numeric">{formatPrice(currency)(priceValue(r,currency,'output'))}</td><td className="numeric">{short(r.context_length)}</td></tr>)}</tbody></table></div>}</>)}
 </>}
 </main>
 <footer className="frame footer"><div className="footer-summary"><span>{t.snapshot}: {date(page==='pricing'?modelData.data?.prices.updated_at:page==='usage'?modelData.data?.trends.updated_at:status.data?.updatedAt)}</span><span>{page==='opensource'?'GitHub REST API':page==='pricing'?'LLM Signal':page==='usage'?'OpenRouter':'GitHub · OpenRouter · LLM Signal'}</span><a href="#methodology" onClick={()=>{document.getElementById("methodology").open=true}}>{t.sourceDetails}<ArrowUpRightIcon size={14}/></a><span className="footer-motto">{t.footerBrand}</span></div><details id="methodology"><summary>{t.methodology}</summary><div className="method-content"><p>{t.snapshotNote}</p><div className="method-grid"><section><h3>{t.opensource}</h3><p>{t.githubMethod}</p><p>{t.review}</p><a href="https://kejunzheng.github.io/penguin-ranking-preview/" target="_blank" rel="noreferrer">{t.githubData}<ArrowUpRightIcon size={14}/></a><p>{t.updated}: {date(status.data?.updatedAt)}</p></section><section><h3>{t.usage} / {t.pricing}</h3><p>{t.usageMethod}</p><p>{t.pricingMethod}</p><a href="https://h5.news.qq.com/qqfile/openrouterllm/model-trends.html" target="_blank" rel="noreferrer">{t.modelData}<ArrowUpRightIcon size={14}/></a><p>{t.usage}: {date(modelData.data?.trends.updated_at)} · {t.pricing}: {date(modelData.data?.prices.updated_at)}</p></section></div></div></details></footer>
 <dialog ref={dialog} onCancel={()=>setModal(null)} onClick={e=>{if(e.target===dialog.current)setModal(null)}}><button className="icon-button modal-close" aria-label={t.close} onClick={()=>setModal(null)}><XIcon size={24}/></button>{modal&&<><p className="eyebrow">{modal.type==='project'?t.details:t.priceDetails}</p><h2>{modal.item.name}</h2>{modal.type==='project'?<><p className="modal-description">{lang==='zh'?(modal.item.capabilitiesZh?.[0]||modal.item.descriptionZh):modal.item.descriptionEn}</p><dl>{[[t.repository,modal.item.fullName],[t.stars,number(modal.item.stars)],[t.growth,'+'+number(modal.item.starGrowth)],[t.forks,number(modal.item.forks)],[t.language,modal.item.language],[t.license,modal.item.license]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v||'—'}</dd></div>)}</dl><p className="quiet">{t.previewNotice}</p></>:<><p>{modal.item.provider_name} · {t.perMillion}</p><dl>{[[t.input,formatPrice(currency)(priceValue(modal.item,currency,'input'))],[t.output,formatPrice(currency)(priceValue(modal.item,currency,'output'))],[t.context,short(modal.item.context_length)],[t.updated,date(modal.item.latest?.date)],[t.tools,modal.item.supports_tools?t.yes:t.no],[t.vision,modal.item.supports_vision?t.yes:t.no]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>{modal.item.has_price_tiers&&<p>{t.tiered}</p>}<p className="quiet">{t.officialNote}</p></>}</>}</dialog>
 </>
}
function Search({value,onChange,label}){return <label className="search"><MagnifyingGlassIcon size={19}/><input aria-label={label} placeholder={label} value={value} onChange={e=>onChange(e.target.value)}/>{value&&<button aria-label="Clear / 清除" onClick={()=>onChange('')}><XIcon/></button>}</label>}
