import React,{useMemo,useState} from 'react';
import {CheckIcon,MagnifyingGlassIcon,XIcon} from '@phosphor-icons/react';
import {benchmarkCutoff,filterBenchmarkModels,resolveBenchmarkModel} from './benchmark-data';

const groupOrder=['综合','Coding','知识','推理','视觉理解','Agent能力','电脑应用','长上下文'];
const groupMeta={
 '综合':{en:'Overall',color:'#e8f1ff'},Coding:{en:'Coding',color:'#e9f7f3'},'知识':{en:'Knowledge',color:'#fff5db'},'推理':{en:'Reasoning',color:'#f1edff'},'视觉理解':{en:'Vision',color:'#e8f6ff'},'Agent能力':{en:'Agent',color:'#ffede8'},'电脑应用':{en:'Computer use',color:'#edf3f5'},'长上下文':{en:'Long context',color:'#f7efe4'}
};
const evidence={
 lmarena_text_overall:['真实用户匿名双模型对战，衡量开放对话的总体偏好。','机器分数不能取代用户体验，它提供模型是否好用的人类视角。','高频动态','官方众包盲测','Elo、票数与置信区间'],
 aa_intelligence_index:['独立第三方汇总多项标准化评测的综合指数。','避免单一厂商或题库决定结论，观察能力广度与均衡性。','持续维护','独立第三方评测','指数版本、子项权重与模型模式'],
 livebench_overall:['以持续更新的新题评测多项通用能力。','动态题目机制降低训练污染，验证前沿模型的真实泛化。','版本制','官方题集 release','release 版本、任务集与 metric'],
 swe_bench_verified:['真实 GitHub issue、代码库与测试验证。','工程修复而非玩具题，是代码 Agent 最具现实意义的硬指标。','结果新增时更新','官方任务集与公开结果','agent harness、patch policy 与 run date'],
 livecodebench:['持续收集竞赛新题，测试算法与代码正确性。','比经典旧题更抗污染，检验实时 coding 推理。','滚动题窗','官方题集与公开结果','题目时间窗、pass@k 与采样设置'],
 aider_polyglot:['在既有项目中跨语言编辑代码并验证修改。','真实开发更多是改对已有代码，而非从零生成片段。','结果新增时更新','Aider 官方榜单','Aider 版本、编辑格式与反馈轮次'],
 mmlu_pro:['跨学科、多选项的专业知识与推理。','在传统 MMLU 趋于饱和后提高难度并保留广覆盖。','结果新增时更新','官方题集与公开结果','CoT、tools、few-shot 与 run date'],
 gpqa_diamond:['研究生级物理、化学、生物专业问答。','补足广泛知识，考察硬科学深度和专业门槛。','结果新增时更新','官方题集与公开结果','Diamond 子集、closed-book 与 tools'],
 simpleqa_verified:['短答案事实准确性与幻觉控制。','直接检验说得像真的但事实错误这一常见风险。','低频汇总','验证结果聚合','版本、核验规则与具体指标'],
 humanitys_last_exam:['覆盖多领域的专家级高难问题。','前沿模型仍能拉开差距，是高难综合推理的压力测试。','版本与结果并行','官方题集与公开结果','closed-book、tools、文本或多模态'],
 frontiermath:['专家设计、可精确判分的研究级数学题。','比竞赛数学更难，私有题集降低记忆化刷分。','版本制','Epoch benchmark 与结果提交','版本、题目层级与 private subset'],
 arc_agi_2:['从少量示例归纳新规则的抽象图形任务。','较少依赖知识库存量，直接检验陌生规则下的泛化。','提交结果更新','ARC Prize 官方结果','成本、时间预算与 harness'],
 mmmu_pro:['学术图表、示意图与多学科图文推理。','检验看懂视觉材料后能否继续推理。','结果新增时更新','官方题集与公开结果','图文输入、Python/tools 与 prompt'],
 mathvista:['几何、图表、科学图像中的数学推理。','区分视觉识别与对结构、数量和逻辑的理解。','低频汇总','官方题集与公开结果','testmini/test、CoT 与 OCR/tool'],
 videommmu:['理解视频中的知识、时间变化和迁移应用。','补足静态图之外的时序视觉理解。','结果新增时更新','官方题集与公开结果','视频采样、字幕/音频与 prompt'],
 terminal_bench_4:['在终端中多步调用工具完成可验证任务。','Agent 的关键是完成任务，而非生成看似合理的计划。','版本制','官方 submission JSON','agent system、trials、timeout 与成本'],
 bfcl_v4:['评估函数/API 选择、参数、多工具协作与拒调。','工具调用是智能体接入真实系统的可靠性门槛。','低频维护','Berkeley 官方 leaderboard','版本、类别、工具定义与匹配指标'],
 gaia:['多步骤推理、检索、文件与工具协作。','观察完整 Agent 系统能否完成开放式任务。','结果新增时更新','官方 public-results 数据集','Agent 系统、工具栈、prompt 与任务等级'],
 osworld:['真实操作系统与桌面软件的 GUI 操作。','衡量模型能否看屏、点击、输入并达成最终状态。','逐条提交更新','官方榜单与提交结果','版本、OS、steps 与成功指标'],
 osworld_2:['跨应用、长周期、动态环境的复杂办公任务。','从会点软件升级为完成完整工作流。','版本制','官方 benchmark 与聚合结果','strict/partial 与 step budget'],
 androidworld:['在安卓模拟器和移动应用中完成真实任务。','补足桌面之外的移动端 GUI 操作能力。','社区提交更新','官方公开结果','屏幕表示、trials 与轨迹链接'],
 ruler:['长文本中的检索、聚合、多跳追踪与上下文衰减。','标称 context window 不等于真实可用长度。','结果新增时更新','NVIDIA 题集与论文结果','context length、tasks 与 precision'],
 longbench_v2:['面向真实长文、多文档的深度理解任务。','与合成任务互补，验证复杂文档阅读能力。','结果新增时更新','官方题集与公开结果','版本、上下文长度、CoT 与任务切片'],
 aa_lcr:['独立第三方的长上下文推理评测。','提供学术榜单之外的第三方交叉验证。','持续维护','Artificial Analysis','版本、thinking level 与 no-tools 口径']
};
const englishSummary={
 lmarena_text_overall:'Anonymous head-to-head user preference for open-ended conversation.',aa_intelligence_index:'A third-party composite index across standardized evaluations.',livebench_overall:'Continuously refreshed tasks for general capability.',swe_bench_verified:'Real GitHub issues resolved and verified by repository tests.',livecodebench:'Fresh programming problems that test algorithmic correctness.',aider_polyglot:'Cross-language code editing in existing projects.',mmlu_pro:'Professional knowledge and reasoning across academic fields.',gpqa_diamond:'Graduate-level physics, chemistry and biology questions.',simpleqa_verified:'Short-answer factual accuracy and hallucination control.',humanitys_last_exam:'Expert-level questions across many domains.',frontiermath:'Research-level mathematics with exact grading.',arc_agi_2:'Abstract rule induction from a few examples.',mmmu_pro:'Multidisciplinary reasoning over images and diagrams.',mathvista:'Mathematical reasoning over charts and scientific images.',videommmu:'Knowledge and temporal reasoning in video.',terminal_bench_4:'Verifiable multi-step work in a terminal.',bfcl_v4:'Function selection, parameters and multi-tool reliability.',gaia:'General agent tasks combining search, files and tools.',osworld:'GUI work in real operating systems and desktop apps.',osworld_2:'Long, cross-app workflows in dynamic environments.',androidworld:'Real tasks in Android apps and emulators.',ruler:'Retrieval and multi-hop tracking over long contexts.',longbench_v2:'Deep understanding of long documents and multi-document inputs.',aa_lcr:'Independent third-party long-context reasoning evaluation.'
};

const formatDate=(value,lang)=>value?new Intl.DateTimeFormat(lang==='zh'?'zh-CN':'en-US',{year:'numeric',month:'2-digit',day:'2-digit',timeZone:'UTC'}).format(new Date(value+'T00:00:00Z')):'—';
const shiftLabel=(preset,lang)=>({zh:{latest:'最新',week:'7 天前',month:'30 天前',quarter:'3 个月前'},en:{latest:'Latest',week:'7 days ago',month:'30 days ago',quarter:'3 months ago'}}[lang][preset]);

export default function BenchmarkExplorer({data,lang}){
 const zh=lang==='zh',latest=data.generated_at.slice(0,10),benchmarkIds=data.benchmarks.map(b=>b.id);
 const defaultCustomStart=benchmarkCutoff(latest,'month');
 const [type,setType]=useState('all'),[region,setRegion]=useState('all'),[coverage,setCoverage]=useState('all'),[preset,setPreset]=useState('latest');
 const [customRange,setCustomRange]=useState({start:defaultCustomStart,end:latest}),[customDraft,setCustomDraft]=useState({start:defaultCustomStart,end:latest}),[customOpen,setCustomOpen]=useState(false);
 const [selected,setSelected]=useState([]),[search,setSearch]=useState(''),[pickerOpen,setPickerOpen]=useState(false),[expanded,setExpanded]=useState(null),[sortBy,setSortBy]=useState(null);
 const cutoff=benchmarkCutoff(latest,preset,customRange.end),rangeStart=preset==='custom'?customRange.start:null;
 const resolved=useMemo(()=>data.models.map(model=>resolveBenchmarkModel(model,benchmarkIds,cutoff,rangeStart)),[data.models,cutoff,rangeStart]);
 const modelPool=resolved.filter(model=>model.coverage>0);
 let rows=filterBenchmarkModels(resolved,{type,region,coverage,selected});
 if(sortBy)rows=[...rows].sort((a,b)=>(a.results[sortBy]?.rank??Infinity)-(b.results[sortBy]?.rank??Infinity)||b.coverage-a.coverage||a.name.localeCompare(b.name));
 else rows=[...rows].sort((a,b)=>b.coverage-a.coverage||a.name.localeCompare(b.name));
 const groups=groupOrder.map(name=>({name,...groupMeta[name],benchmarks:data.benchmarks.filter(b=>b.category===name)}));
 const suggestions=modelPool.filter(model=>(model.name+' '+model.organization).toLowerCase().includes(search.toLowerCase())).slice(0,12);
 const shownBenchmarks=groups.flatMap(group=>expanded===group.name?group.benchmarks:group.benchmarks.slice(0,1));
 const benchmarkDate=id=>resolved.map(model=>model.results[id]?.date).filter(Boolean).sort().at(-1)||data.benchmarks.find(b=>b.id===id)?.latest_date;
 function toggleModel(id){setSelected(current=>current.includes(id)?current.filter(item=>item!==id):current.length<5?[...current,id]:current)}
 return <section className="benchmark-explorer">
  <div className="benchmark-toolbar" aria-label={zh?'榜单筛选与时间设置':'Ranking filters and snapshot'}>
   <div className="benchmark-filters">
    <label><span>{zh?'模型类型':'Model type'}</span><select value={type} onChange={e=>setType(e.target.value)}><option value="all">{zh?'全部':'All'}</option><option value="closed">{zh?'闭源':'Closed'}</option><option value="open">{zh?'开放权重':'Open weights'}</option></select></label>
    <label><span>{zh?'地区':'Region'}</span><select value={region} onChange={e=>setRegion(e.target.value)}><option value="all">{zh?'全球':'Global'}</option><option value="china">{zh?'中国模型':'China'}</option><option value="overseas">{zh?'海外模型':'Outside China'}</option></select></label>
    <label><span>{zh?'覆盖度':'Coverage'}</span><select value={coverage} onChange={e=>setCoverage(e.target.value)}><option value="all">{zh?'全部上榜':'All ranked'}</option><option value="high">{zh?'高覆盖（12+）':'High coverage (12+)'}</option><option value="focused">{zh?'单项／专项':'Focused'}</option></select></label>
    <div className="benchmark-compare"><span>{zh?'模型对比':'Compare'}</span><div className="benchmark-search" onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))setPickerOpen(false)}}><MagnifyingGlassIcon size={15}/><input value={search} onFocus={()=>setPickerOpen(true)} onChange={e=>{setSearch(e.target.value);setPickerOpen(true)}} placeholder={zh?'搜索模型，最多选择 5 个':'Search, up to 5 models'} aria-label={zh?'搜索并选择最多五个模型进行对比':'Search and select up to five models'}/>{search&&<button aria-label={zh?'清除搜索':'Clear search'} onClick={()=>setSearch('')}><XIcon size={14}/></button>}
     {pickerOpen&&<div className="benchmark-suggestions" onMouseDown={e=>e.preventDefault()}>{suggestions.map(model=><button key={model.id} onClick={()=>toggleModel(model.id)} aria-pressed={selected.includes(model.id)} disabled={!selected.includes(model.id)&&selected.length>=5}><span className="benchmark-check">{selected.includes(model.id)&&<CheckIcon weight="bold"/>}</span><span><strong>{model.name}</strong><small>{model.organization} · {model.coverage}/24</small></span></button>)}{!suggestions.length&&<p>{zh?'未找到匹配模型':'No matching models'}</p>}</div>}</div></div>
    {selected.length>0&&<div className="benchmark-chips">{selected.map(id=>{const model=modelPool.find(item=>item.id===id);return model&&<button key={id} onClick={()=>toggleModel(id)}>{model.name}<XIcon size={12}/></button>})}</div>}
   </div>
   <div className="benchmark-snapshots" role="group" aria-label={zh?'时间快照':'Time snapshot'}>{['latest','week','month','quarter'].map(item=><button key={item} aria-pressed={preset===item} onClick={()=>{setPreset(item);setCustomOpen(false)}}>{shiftLabel(item,lang)}</button>)}<div className={'benchmark-custom-date '+(preset==='custom'?'active':'')} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))setCustomOpen(false)}}><button type="button" aria-haspopup="dialog" aria-expanded={customOpen} aria-pressed={preset==='custom'} onClick={()=>{setCustomDraft(customRange);setCustomOpen(open=>!open)}}>{preset==='custom'?`${formatDate(customRange.start,lang)} — ${formatDate(customRange.end,lang)}`:(zh?'自定义':'Custom')}</button>{customOpen&&<div className="benchmark-custom-panel" role="dialog" aria-label={zh?'自定义日期区间':'Custom date range'}><label><span>{zh?'开始日期':'Start date'}</span><input type="date" min="2025-01-01" max={customDraft.end} value={customDraft.start} onChange={e=>setCustomDraft(range=>({...range,start:e.target.value}))}/></label><span className="benchmark-range-arrow">→</span><label><span>{zh?'结束日期':'End date'}</span><input type="date" min={customDraft.start} max={latest} value={customDraft.end} onChange={e=>setCustomDraft(range=>({...range,end:e.target.value}))}/></label><button type="button" disabled={!customDraft.start||!customDraft.end||customDraft.start>customDraft.end} onClick={()=>{setCustomRange(customDraft);setPreset('custom');setCustomOpen(false)}}>{zh?'应用':'Apply'}</button></div>}</div></div>
  </div>
  <p className="benchmark-status">{zh?'当前查看：':'Viewing: '}<strong>{preset==='latest'?(zh?`最新快照（${formatDate(latest,lang).replaceAll('/','.')}）`:`Latest snapshot (${formatDate(latest,lang)})`):preset==='custom'?`${formatDate(customRange.start,lang)} — ${formatDate(customRange.end,lang)}`:zh?`截至 ${formatDate(cutoff,lang)}`:`Through ${formatDate(cutoff,lang)}`}</strong>{preset==='custom'?(zh?'。每列保留其在该区间内最近一次有效结果。':'. Each column keeps its latest valid result within this range.'):(zh?'。每列保留其在该时点或此前最近一次有效结果。':'. Each column keeps its latest valid result at or before this date.')}{zh?'每类默认显示 1 项代表 benchmark':' Each category shows one representative benchmark by default.'}</p>
  {selected.length>0&&<button className="benchmark-clear" onClick={()=>setSelected([])}>{zh?'显示全部模型':'Show all models'}</button>}
  <div className="benchmark-table-wrap"><table className="benchmark-table"><thead><tr><th rowSpan="2" className="benchmark-model-col">{zh?'模型产品 / SKU':'Model product / SKU'}</th>{groups.map(group=><th key={group.name} colSpan={expanded===group.name?3:1} className="benchmark-group" style={{'--group-color':group.color}}><button onClick={()=>setExpanded(expanded===group.name?null:group.name)} aria-expanded={expanded===group.name}>{zh?group.name:group.en}<span>{expanded===group.name?'−':'＋'}</span></button></th>)}</tr><tr>{groups.flatMap(group=>(expanded===group.name?group.benchmarks:group.benchmarks.slice(0,1)).map(benchmark=><th key={benchmark.id} className="benchmark-column" style={{'--group-color':group.color}}><button onClick={()=>setSortBy(sortBy===benchmark.id?null:benchmark.id)} aria-pressed={sortBy===benchmark.id}><strong>{benchmark.display_name}</strong><small>{formatDate(benchmarkDate(benchmark.id),lang)}</small><span>{sortBy===benchmark.id?(zh?'已排序 ↑':'Sorted ↑'):(zh?'排序 ↕':'Sort ↕')}</span></button></th>))}</tr></thead><tbody>{rows.map(model=><tr key={model.id}><td><div className="benchmark-model"><i className={model.region}/><div><strong>{model.name}</strong><small>{model.organization} · {model.openWeights?(zh?'开放权重':'Open weights'):(zh?'闭源':'Closed')} · {zh?'入榜':'Coverage'} {model.coverage}/24</small></div></div></td>{shownBenchmarks.map(benchmark=>{const result=model.results[benchmark.id];return <td key={benchmark.id} style={{'--group-color':groupMeta[benchmark.category].color}}>{result?<a className={'benchmark-rank rank-'+Math.min(result.rank,4)} href={result.source||benchmark.official_url} target="_blank" rel="noreferrer" title={`${model.name} · ${benchmark.canonical_name} · ${result.date}`}>#{result.rank}</a>:<span className="benchmark-na">—</span>}</td>})}</tr>)}</tbody></table>{!rows.length&&<div className="benchmark-empty-state">{zh?'当前筛选条件下暂无模型。':'No models match these filters.'}</div>}</div>
  <p className="benchmark-source-line">{zh?'数据来源：':'Source: '}<a href={data.source_page} target="_blank" rel="noreferrer">{zh?'企鹅模型能力榜公开数据集':'Penguin Model Capability Ranking public dataset'}</a> · {zh?'数据更新：':'Data updated: '}{formatDate(latest,lang)}</p>
  <div className="benchmark-reading-guide"><div className="benchmark-number-guide"><p><mark>{zh?'数字说明':'Number guide'}</mark><b>#1、#2、#3…</b>{zh?'为该模型在对应 benchmark 公开榜单中的名次，数字越小排名越靠前。':'are the model’s positions on the corresponding public benchmark leaderboard; lower is better.'}</p><p><b>2026-06-25</b>{zh?'等日期为该列当前可核实的最近一批结果日期，不代表全站更新时间或统一评测日。':'is an example of the latest verifiable result date for that column, not the site update time or a shared evaluation date.'}</p><p><b>—</b>{zh?'表示未收录到该 benchmark 的公开结果。':'means no public result for that benchmark is currently included.'}</p></div><p className="benchmark-comparison-note">{zh?'排名仅在相同 benchmark、相同公开榜单和相近版本条件下具有可比性；单元格 hover 可查看来源与采集说明。':'Ranks are comparable only within the same benchmark, public leaderboard and similar model versions; hover a cell to inspect its source and collection note.'}</p><div className="benchmark-pool-stats"><div><strong>{rows.length}</strong><span>{zh?'当前显示模型':'Models shown'}</span></div><div><strong>{data.models.length}</strong><span>{zh?'并集模型池':'Union model pool'}</span></div><div><strong>{benchmarkIds.length}</strong><span>{zh?'榜单独立时间戳':'Independent timestamps'}</span></div><p><b>{zh?'完整性口径：':'Completeness: '}</b>{zh?'先抓取每个 benchmark 的公开 leaderboard，再对模型名做归一化合并。同一模型不同推理档位、版本、日期先保留为独立行，后续可在模型详情页合并查看。':'Each public benchmark leaderboard is collected first, then model names are normalized and merged. Different reasoning tiers, versions and dates remain independent rows and may later be grouped on a model detail page.'}</p></div></div>
  <details className="data-notes benchmark-notes" open><summary>{zh?'数据来源与统计口径':'Sources & methodology'}</summary><div className="data-notes-body"><section className="data-note-section"><h3>{zh?'数据来源':'Data sources'}</h3><p>{zh?'本榜呈现 8 类能力、24 项公开 benchmark 的可核实结果，按权威性、新鲜度与真实任务相关性遴选。优先采用官方 leaderboard、API、发布文件及协议完整、可追溯的独立实测；厂商自报或协议不全的结果仅作线索。':'This ranking presents verifiable results from 24 public benchmarks across eight capability groups, selected for authority, freshness and relevance to real tasks. Official leaderboards, APIs, release files and independently reproducible evaluations with complete protocols are prioritized; vendor-reported or incompletely documented results are treated only as leads.'}</p></section><section className="data-note-section"><h3>{zh?'统计口径':'Methodology'}</h3><p>{zh?'数据按日生成快照、按周全量校验；表头日期为各列当前可核实的最近有效结果日期，新模型、官方新版本或可信结果出现时补采。首页以可独立选择的产品 SKU 为行，旗舰、mini / nano、不同参数、模态及推理配置不合并；主榜须覆盖至少 2 项已导入 benchmark，且发布日期距快照不超过 18 个月。排名仅限同一 benchmark、版本和指标协议下比较，不跨榜加总，也不挑选最佳值充当通用成绩；Agent 与电脑应用结果须结合 harness、工具权限、步数、超时和推理预算阅读。':'Data snapshots are generated daily and fully checked weekly. Column dates show the latest verifiable result currently available, with new models, official versions and credible results added as they appear. Rows represent independently selectable product SKUs; flagship, mini or nano variants, parameter sizes, modalities and reasoning configurations are not merged. Main-ranking models must cover at least two imported benchmarks and be released within 18 months of the snapshot. Ranks are compared only within the same benchmark, version and metric protocol; they are not summed across rankings or cherry-picked into a general score. Agent and computer-use results must be read alongside the harness, tool permissions, step limits, timeouts and reasoning budget.'}</p></section><section className="data-note-section"><h3>{zh?'免责声明':'Disclaimer'}</h3><p>{zh?'“—”表示暂未收录可核实公开结果，不代表能力不足。本榜仅供行业观察，不构成采购或投资建议；发现新证据、名称归一化错误或协议不一致时，将保留证据链并修订历史记录。':'A dash means no verifiable public result is currently included; it does not imply weak capability. This ranking is for industry observation only and is not procurement or investment advice. When new evidence, normalization errors or protocol inconsistencies are found, the evidence trail is retained and historical records are revised.'}</p></section></div></details>
  <div className="benchmark-directory"><div className="benchmark-intro compact"><div><p className="eyebrow">BENCHMARK EVIDENCE DIRECTORY</p><h2>{zh?'24 项 benchmark 入选清单':'24 benchmark evidence directory'}</h2></div><p>{zh?'逐项查看能力缺口、更新频次、结果口径与不可替代性。':'Review the capability gap, update cadence and protocol of every benchmark.'}</p></div><div className="benchmark-card-grid">{data.benchmarks.map(benchmark=>{const detail=evidence[benchmark.id]||[];return <details className="benchmark-card" key={benchmark.id}><summary><span style={{background:groupMeta[benchmark.category].color}}>{zh?benchmark.category:groupMeta[benchmark.category].en}</span><h3>{benchmark.canonical_name}</h3><p>{zh?detail[0]:englishSummary[benchmark.id]}</p><b>{zh?'展开档案 +':'Open profile +'}</b></summary><div><dl><div><dt>{zh?'不可替代性':'Why it matters'}</dt><dd>{zh?detail[1]:'Adds a distinct, publicly verifiable view of model capability.'}</dd></div><div><dt>{zh?'更新频次':'Update cadence'}</dt><dd>{zh?detail[2]:benchmark.update_mode.replaceAll('_',' ')}</dd></div><div><dt>{zh?'结果来源':'Result source'}</dt><dd>{zh?detail[3]:'Public benchmark results'}</dd></div><div><dt>{zh?'读榜注意':'Reading note'}</dt><dd>{zh?detail[4]:'Check version, configuration and protocol before comparison.'}</dd></div></dl><button type="button" className="benchmark-card-collapse" onClick={event=>event.currentTarget.closest('details').removeAttribute('open')}>{zh?'收起档案 −':'Close profile −'}</button></div></details>})}</div></div>
  <div className="benchmark-prototype-footer"><span>{zh?'企鹅智库｜榜单 · Model Capability Ranking Prototype':'Penguin Intelligence | Rankings · Model Capability Ranking Prototype'}</span><span>{zh?'数据来源：各 benchmark 官方公开 leaderboard / release CSV / 可核验第三方公开快照':'Sources: official benchmark leaderboards / release CSVs / verifiable public third-party snapshots'}</span></div>
 </section>;
}
