import {useEffect,useRef,useMemo} from 'react';
import {ArrowUpRightIcon} from '@phosphor-icons/react';
import ModelLogo from './ModelLogo';
import sources from './price-sources.json';
import {modelPrices,priceHistory} from './price-details';
const text={zh:{input:'输入价格',output:'输出价格',blended:'综合价格',formula:'综合价格按输入 : 输出 = 3 : 1 计算',unit:'每百万 Token',free:'免费',context:'上下文长度',weights:'模型权重',open:'开放权重',closed:'闭源',tools:'工具调用',vision:'视觉能力',yes:'支持',no:'不支持',updated:'价格更新于',released:'发布于',unavailable:'未提供',tier:'阶梯计价 · 当前展示最低计费档，实际价格随输入或输出长度变化。',tierLabel:'展示档位',call:'在哪里调用',website:'官网',official:'官方 API',third:'第三方平台',platformNote:'入口按厂商提供，具体模型可用性请在平台确认。',history:'近 30 天价格走势',historyNote:'按价格快照日期回看；仅展示已记录的数据。',empty:'暂无历史数据',source:'数据来源：原站发布的厂商价格快照',releaseSource:'发布日期沿用原站记录',fx:'美元历史价格使用快照内汇率换算',currency:'币种'},en:{input:'Input price',output:'Output price',blended:'Blended price',formula:'Blended price uses a 3:1 input-to-output ratio',unit:'Per 1M tokens',free:'Free',context:'Context window',weights:'Model weights',open:'Open weights',closed:'Proprietary',tools:'Tool calling',vision:'Vision',yes:'Supported',no:'Not supported',updated:'Price updated',released:'Released',unavailable:'Not provided',tier:'Tiered pricing · showing the lowest listed tier. Actual pricing varies with input or output length.',tierLabel:'Displayed tier',call:'Where to use',website:'Website',official:'Official API',third:'Third-party platforms',platformNote:'Provider-level links. Check each platform for model availability.',history:'30-day price history',historyNote:'Relative to the price snapshot; recorded observations only.',empty:'No price history yet',source:'Source: provider price snapshots published by the reference site',releaseSource:'Release dates follow the reference site',fx:'USD history uses the exchange rate stored in the snapshot',currency:'Currency'}};
const categories={audio:['语音','Audio'],coding:['编程','Coding'],flagship:['旗舰','Flagship'],lite:['轻量','Lightweight'],'long-context':['长上下文','Long context'],multimodal:['多模态','Multimodal'],reasoning:['推理','Reasoning'],roleplay:['角色','Roleplay'],translation:['翻译','Translation'],vision:['视觉','Vision']};
export default function PriceDetails({model,lang,currency,onCurrency,meta}){
 const t=text[lang],chart=useRef(null),prices=modelPrices(model,currency),history=useMemo(()=>priceHistory(model,currency,meta.usd_to_cny),[model,currency,meta.usd_to_cny]);
 const provider=sources.providers[model.provider],released=model.release_date||sources.releaseDates[model.slug];
 const money=n=>n==null?'—':n===0?t.free:new Intl.NumberFormat(lang==='zh'?'zh-CN':'en-US',{style:'currency',currency,maximumFractionDigits:4,minimumFractionDigits:2}).format(n);
 useEffect(()=>{let disposed=false,instance,observer;if(!history.length)return;import('./chart').then(({createPriceChart})=>{if(disposed)return;instance=createPriceChart(chart.current,history,currency,t);observer=new ResizeObserver(()=>instance.resize());observer.observe(chart.current)});return()=>{disposed=true;observer?.disconnect();instance?.dispose()}},[history,currency,lang]);
 return <><div className="price-detail-header"><ModelLogo item={model} lang={lang} large/><div><p className="eyebrow">{lang==='zh'?'模型价格详情':'MODEL PRICING'}</p><h2 id="price-detail-title">{model.name}</h2><p>{model.provider_name} · {categories[model.category]?.[lang==='zh'?0:1]||model.category}</p></div></div>
 <div className="price-detail-body"><div className="detail-currency"><span>{t.unit}</span><div className="segmented" aria-label={t.currency}>{['USD','CNY'].map(c=><button key={c} onClick={()=>onCurrency(c)} aria-pressed={currency===c}>{c}</button>)}</div></div>
 <div className="price-metrics">{['input','output','blended'].map(key=><div key={key}><span>{t[key]}</span><strong className={prices[key]===0?'free-price':''}>{money(prices[key])}</strong></div>)}</div><p className="price-formula">{t.formula}</p>
 {model.has_price_tiers&&<div className="tier-notice"><p>{t.tier}</p>{model.price_tier_label&&<strong>{t.tierLabel}: {model.price_tier_label}</strong>}</div>}
 <dl className="price-facts">{[[t.context,model.context_length?new Intl.NumberFormat('en',{notation:'compact'}).format(model.context_length):t.unavailable],[t.weights,model.is_open_source?t.open:t.closed],[t.tools,model.supports_tools?t.yes:t.no],[t.vision,model.supports_vision?t.yes:t.no],[t.updated,model.latest?.date||t.unavailable],[t.released,released||t.unavailable]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>
 {provider&&<section className="call-platforms"><div className="section-head"><h3>{t.call}</h3><a href={provider.websiteUrl} target="_blank" rel="noopener noreferrer">{t.website}<ArrowUpRightIcon size={14}/></a></div>{['official','third_party'].map(type=>{const platforms=provider.platforms.filter(p=>p.type===type);return platforms.length>0&&<div className="platform-group" key={type}><p>{type==='official'?t.official:t.third}</p><div>{platforms.map(p=><a key={p.url} href={p.url} target="_blank" rel="noopener noreferrer">{lang==='zh'?p.name:p.nameEn}<ArrowUpRightIcon size={14}/></a>)}</div></div>})}<p className="quiet">{t.platformNote}</p></section>}
 <section className="price-history"><h3>{t.history}</h3><p>{t.historyNote}</p>{history.length?<div ref={chart} className="price-history-chart" role="img" aria-label={model.name+' '+t.history}/>:<div className="history-empty">{t.empty}</div>}{currency==='USD'&&<p className="quiet">{t.fx} · 1 USD = {meta.usd_to_cny} CNY</p>}</section><p className="detail-source">{t.source} · {t.releaseSource}</p></div></>;
}
