import {useEffect,useMemo,useState} from 'react';
import {ArrowUpRightIcon,MagnifyingGlassIcon,DownloadSimpleIcon,StarIcon} from '@phosphor-icons/react';

const categoryNames={'dev-programming':['开发编程','Development'],'content-creation':['内容创作','Content'],'office-efficiency':['办公效率','Productivity'],'data-analysis':['数据分析','Data'],'knowledge-management':['知识管理','Knowledge'],'ai-agent':['AI Agent','AI Agent'],'education-learning':['教育学习','Education'],'life-services':['生活服务','Lifestyle'],'industry-professional':['行业专业','Industry'],'business-ops':['商业运营','Business operations'],'design-media':['设计创意','Design & media'],education:['教育学习','Education'],'it-ops-security':['IT 运维与安全','IT, ops & security'],'life-service':['生活服务','Lifestyle'],professional:['行业专业','Professional'],uncategorized:['未分类','Uncategorized']};
const compact=value=>new Intl.NumberFormat('zh-CN',{notation:'compact',maximumFractionDigits:1}).format(value||0);

export default function SkillhubExplorer({data,lang}){
 const zh=lang==='zh',[mode,setMode]=useState('trending'),[query,setQuery]=useState(''),[category,setCategory]=useState('all'),[page,setPage]=useState(1);
 const all=data[mode]||[],categories=useMemo(()=>[...new Set([...data.trending,...data.downloads].map(item=>item.category))].sort(),[data]);
 const rows=useMemo(()=>all.filter(item=>(category==='all'||item.category===category)&&`${item.name} ${item.description} ${item.id}`.toLowerCase().includes(query.toLowerCase())),[all,category,query]);
 const pageSize=25,pages=Math.max(1,Math.ceil(rows.length/pageSize)),shown=rows.slice((page-1)*pageSize,page*pageSize);
 useEffect(()=>setPage(1),[mode,query,category]);
 return <section className="skillhub-explorer"><div className="skillhub-toolbar"><div className="segmented skillhub-modes" aria-label={zh?'榜单类型':'Ranking type'}><button aria-pressed={mode==='trending'} onClick={()=>setMode('trending')}>{zh?'近期飙升':'Trending now'}</button><button aria-pressed={mode==='downloads'} onClick={()=>setMode('downloads')}>{zh?'下载量 Top 1000':'Top 1,000 downloads'}</button></div><label className="search"><MagnifyingGlassIcon size={18}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder={zh?'搜索 Skill 名称或关键词…':'Search skills or keywords…'} aria-label={zh?'搜索 Skill':'Search skills'}/></label><select value={category} onChange={event=>setCategory(event.target.value)} aria-label={zh?'场景分类':'Category'}><option value="all">{zh?'全部分类':'All categories'}</option>{categories.map(key=><option value={key} key={key}>{categoryNames[key]?.[zh?0:1]||key}</option>)}</select></div>
  <div className="section-head skillhub-results"><strong>{rows.length} {zh?'项 Skill':'skills'}</strong><span>{mode==='trending'?(zh?'按 SkillHub 近期飙升公开榜排序':'SkillHub public trending order'):(zh?'按公开下载量排序，仅保留前 1000':'Sorted by public downloads; top 1,000 only')}</span></div>
  <div className="table-scroll"><table className="skillhub-table"><thead><tr><th>#</th><th>Skill</th><th>{zh?'分类':'Category'}</th><th>{zh?'下载量':'Downloads'}</th><th>{zh?'收藏':'Stars'}</th><th>{zh?'来源':'Source'}</th></tr></thead><tbody>{shown.map((item,index)=><tr key={item.id}><td className="ranking">{String((page-1)*pageSize+index+1).padStart(2,'0')}</td><td><a className="skillhub-name" href={item.url} target="_blank" rel="noreferrer"><strong>{item.name}</strong><ArrowUpRightIcon size={15}/></a><p>{item.description||'—'}</p><small>{item.id}</small></td><td><span className="skillhub-category">{categoryNames[item.category]?.[zh?0:1]||item.category}</span></td><td className="numeric"><DownloadSimpleIcon size={15}/>{compact(item.downloads)}</td><td className="numeric"><StarIcon size={15}/>{compact(item.stars)}</td><td>{item.source}</td></tr>)}</tbody></table></div>
  <nav className="skillhub-pagination" aria-label={zh?'SkillHub榜分页':'SkillHub ranking pagination'}><button disabled={page===1} onClick={()=>setPage(value=>Math.max(1,value-1))}>{zh?'上一页':'Previous'}</button><span>{page} / {pages}</span><button disabled={page===pages} onClick={()=>setPage(value=>Math.min(pages,value+1))}>{zh?'下一页':'Next'}</button></nav>
  <details className="data-notes" open><summary>{zh?'数据来源与统计口径':'Sources & methodology'}</summary><div className="data-notes-body"><section className="data-note-section"><h3>{zh?'数据来源':'Data source'}</h3><p>{zh?'数据来自 SkillHub 公开榜单与公开 API。技能名称、分类、简介、收藏数和下载量以抓取时的公开记录为准。':'Data comes from SkillHub public rankings and API records at the snapshot time.'}</p></section><section className="data-note-section"><h3>{zh?'统计口径':'Methodology'}</h3><p>{zh?'仅展示 SkillHub 的近期飙升榜 100 项，以及按公开下载量排序的前 1000 项。两个榜单独立排序，不将下载量、收藏数或评分合并为总分。':'Shows the 100-item public trending list and the top 1,000 by public downloads. The rankings remain separate.'}</p></section><section className="data-note-section"><h3>{zh?'免责声明':'Disclaimer'}</h3><p>{zh?'热度和下载量不代表安全性、兼容性或实际效果。安装前请核对来源、权限、脚本内容及 API Key 要求。':'Popularity and downloads do not establish safety, compatibility or effectiveness. Review permissions and code before installation.'}</p></section><p className="data-notes-sources">{zh?'数据来源：':'Source: '}<a href={data.source_url} target="_blank" rel="noreferrer">SkillHub</a> · {zh?'数据更新：':'Updated: '}{data.generated_at.slice(0,10)}</p></div></details></section>;
}
